const List = [
  {
    _id: 0,
    name: "타로상징 완전 정복",
    img: "book01.jpg",
    category: "book",
    price: "10,000",
  },
  {
    _id: 1,
    name: "초심자를 위한 최고의 안내서",
    img: "book02.jpg",
    category: "book",
    price: "12,000",
  },
  {
    _id: 2,
    name: "레노먼드 오라클",
    img: "book03.jpg",
    category: "book",
    price: "10,500",
  },
  {
    _id: 3,
    name: "타로카드 매트릭스",
    img: "book04.jpg",
    category: "book",
    price: "9,000",
  },
  {
    _id: 4,
    name: "슬기로운 타로생활",
    img: "book05.jpg",
    category: "book",
    price: "17,000",
  },
  {
    _id: 5,
    name: "Radiant Rider-Waite",
    img: "book06.jpg",
    category: "book",
    price: "18,000",
  },
  {
    _id: 6,
    name: "파볼레 타로카드",
    img: "card01.jpg",
    category: "card",
    price: "10,600",
  },
  {
    _id: 7,
    name: "로맨틱 타로카드",
    img: "card02.jpg",
    category: "card",
    price: "19,000",
  },
  {
    _id: 8,
    name: "쉐도우 스케이프스 타로카드",
    img: "card03.jpg",
    category: "card",
    price: "16,000",
  },
  {
    _id: 9,
    name: "올드 잉글리쉬 타로카드",
    img: "card04.jpg",
    category: "card",
    price: "28,000",
  },
  {
    _id: 10,
    name: "오쇼젠 타로카드",
    img: "card05.jpg",
    category: "card",
    price: "65,000",
  },
  {
    _id: 11,
    name: "스미스웨이트 타로카드",
    img: "card06.jpg",
    category: "card",
    price: "19,000",
  },
  {
    _id: 12,
    name: "프리즈마 비젼 타로카드",
    img: "card07.jpg",
    category: "card",
    price: "11,500",
  },
  {
    _id: 13,
    name: "에머시스트 룬스톤",
    img: "stone01.jpg",
    category: "stone",
    price: "16,000",
  },
  {
    _id: 14,
    name: "블랙아게이트 룬스톤",
    img: "stone02.jpg",
    category: "stone",
    price: "100,000",
  },
  {
    _id: 15,
    name: "블러드스톤 룬스톤",
    img: "stone03.jpg",
    category: "stone",
    price: "70,000",
  },
  {
    _id: 16,
    name: "해머타이트 룬스톤",
    img: "stone04.jpg",
    category: "stone",
    price: "205,000",
  },
  {
    _id: 17,
    name: "화이트오닉스 룬스톤",
    img: "stone05.jpg",
    category: "stone",
    price: "39,000",
  },
  {
    _id: 18,
    name: "레드카넬리안 룬스톤",
    img: "stone06.jpg",
    category: "stone",
    price: "65,000",
  },
  {
    _id: 19,
    name: "로즈 쿼츠 룬스톤",
    img: "stone07.jpg",
    category: "stone",
    price: "77,000",
  },
];
export default List;
